name: Build and Release QGIS Plugin

on:
  push:
    tags:
      - 'v*'
      - 'version_*'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create clean plugin zip
        run: |
          mkdir build
          cp -r LayerCounter build/LayerCounter
          cd build
          zip -r ../LayerCounter.zip LayerCounter

      - name: Create GitHub Release and upload ZIP
        uses: softprops/action-gh-release@v1
        with:
          files: LayerCounter.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
