name: Build QGIS Plugin

on:
  push:
    tags:
      - 'v*'  # z.B. v0.1

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Rename plugin folder to match QGIS expectations
        run: |
          mv layer_counter LayerCounter

      - name: Create plugin ZIP
        run: |
          zip -r LayerCounter.zip LayerCounter

      - name: Upload plugin ZIP as release asset
        uses: softprops/action-gh-release@v1
        with:
          files: LayerCounter.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
