name: Build and Release QGIS Plugin

on:
  push:
    tags:
      - 'v*'
      - 'version_*'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Zeige Dateistruktur (Debug)
        run: ls -R

      - name: Plugin zippen
        run: zip -r LayerCounter.zip LayerCounter

      - name: Release erstellen + ZIP hochladen
        uses: softprops/action-gh-release@v1
        with:
          files: LayerCounter.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
